context:
  initializer:
    classes: 'com.lhq.boot.demo.initialize.ThirdApplicationContextInitialize'
  listener:
    classes: 'com.lhq.boot.demo.listener.ThirdListener'
operate:
  name: 'lhq'
#这里是我们的yaml配置
lhqPwd: 'lhq03261302'
##配置我们的redis
spring:
  redis:
    database: 0
    port: 6379
    host: 127.0.0.1
